export const db = "procogdb"
export const riskCollection = "risks"
export const solutionCollection = "solutions"
export const commentCollection = "comments"
export const voteCollection = "votes"
export const riskAttachmentBucket = "risk-attachment"